name: nyalcf_core
description: 'Nya LoCyanFrp! core module.'
version: 1.0.6
homepage: https://nyalcf.1l1.icu
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  nyalcf_inject:
    path: ../nyalcf_inject
  dio: ^5.4.1
  archive: ^3.6.1
  logger: ^2.1.0
  crypto: ^3.0.3
  win32_registry: ^1.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
