name: nyalcf_core
description: 'Nya LoCyanFrp! core module.'
version: 2.0.6
homepage: https://nyalcf.1l1.icu
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  nyalcf_env:
    path: ../nyalcf_env
  nyalcf_inject:
    path: ../nyalcf_inject
  dio: ^5.8.0+1
  archive: ^4.0.2
  logger: ^2.5.0
  crypto: ^3.0.6
  win32_registry: ^2.1.0
  shelf_router: ^1.1.4
  shelf: ^1.4.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  import_sorter: ^4.6.0
