name: nyalcf_core
description: A starting point for Dart libraries or applications.
version: 1.0.3
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  dio: ^5.4.1
  path_provider: ^2.1.3
  archive: ^3.4.9
  package_info_plus: ^7.0.0
  logger: ^2.1.0
  crypto: ^3.0.3
  win32_registry: ^1.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
