# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Inject
  - package-ecosystem: "pub"
    directory: "/nyalcf_inject"
    schedule:
      interval: "daily"
    target-branch: "dev"

  # Core
  - package-ecosystem: "pub"
    directory: "/nyalcf_core"
    schedule:
      interval: "daily"
    target-branch: "dev"

  # GUI
  - package-ecosystem: "pub"
    directory: "/nyalcf_gui"
    schedule:
      interval: "daily"
    target-branch: "dev"
  ## UI
  - package-ecosystem: "pub"
    directory: "/nyalcf_gui/nyalcf_ui"
    schedule:
      interval: "daily"
    target-branch: "dev"
  ## Core Extend
  - package-ecosystem: "pub"
    directory: "/nyalcf_gui/nyalcf_inject_extend"
    schedule:
      interval: "daily"
    target-branch: "dev"
  ## Inject Extend
  - package-ecosystem: "pub"
    directory: "/nyalcf_gui/nyalcf_core_extend"
    schedule:
      interval: "daily"
    target-branch: "dev"

  # CLI
  - package-ecosystem: "pub"
    directory: "/nyalcf_cli"
    schedule:
      interval: "daily"
    target-branch: "dev"

  # ENV
  - package-ecosystem: "pub"
    directory: "/nyalcf_env"
    schedule:
      interval: "daily"
    target-branch: "dev"
