# This file configures the static analysis results for your project (errors,
# warnings, and lints).

analyzer:
  exclude:
    - 'tools/**'

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
