name: nyalcf_inject
description: "Nya LoCyanFrp! communication injector module."
version: 0.1.3
homepage: https://nyalcf.1l1.icu
publish_to: 'none'

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
