name: nyalcf_inject
description: "Nya LoCyanFrp! communication injector module."
version: 1.1.1
homepage: https://nyalcf.1l1.icu
publish_to: 'none'

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  nyalcf_core:
    path: ../nyalcf_core
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  import_sorter: ^4.6.0
