name: flutter_app_packager
description: Package your Flutter app into OS-specific bundles (.dmg, .exe, etc.) via Dart or the command line.
version: 0.3.7
homepage: https://github.com/leanflutter/flutter_distributor
publish_to: none

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  app_package_maker:
    path: ../app_package_maker
  archive: ^3.4.10
  io: ^1.0.3
  liquid_engine: ^0.2.2
  msix: ^3.16.6
  path: ^1.8.1
  shell_executor:
    path: ../shell_executor

dev_dependencies:
  dependency_validator: ^3.0.0
