name: flutter_distributor
description: A complete tool for packaging and publishing your Flutter apps.
version: 0.3.7
homepage: https://distributor.leanflutter.org
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/flutter_distributor
issue_tracker: https://github.com/leanflutter/flutter_distributor/issues
publish_to: none

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  app_package_maker:
    path: ../app_package_maker
  app_package_publisher:
    path: ../app_package_publisher
  args: ^2.2.0
  dio: ^5.3.4
  flutter_app_builder:
    path: ../flutter_app_builder
  flutter_app_packager:
    path: ../flutter_app_packager
  flutter_app_publisher:
    path: ../flutter_app_publisher
  logging: ^1.0.2
  path: ^1.8.1
  pubspec_parse: ^1.1.0
  shell_executor:
    path: ../shell_executor
  shell_uikit:
    path: ../shell_uikit
  yaml: ^3.1.0

dev_dependencies:
  dependency_validator: ^3.0.0
  test: ^1.23.1

executables:
  flutter_distributor: main
