name: nyalcf_core_extend
description: "Nya LoCyanFrp! core extend module."
version: 2.0.6
homepage: https://nyalcf.1l1.icu
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  nyalcf_core:
    path: ../../nyalcf_core

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  import_sorter: ^4.6.0