name: nyalcf_env
description: "Nya LoCyanFrp! env module."
version: 2.0.0
homepage: https://nyalcf.1l1.icu
publish_to: 'none'

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  import_sorter: ^4.6.0
