name: nyalcf
description: "[CLI]The next generation of LoCyanFrp launcher."
version: 1.0.1+4
homepage: https://nyalcf.1l1.icu
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  nyalcf_core:
    path: ../nyalcf_core
  nyalcf_env:
    path: ../nyalcf_env
  nyalcf_inject:
    path: ../nyalcf_inject
  nyalcf_core_extend:
    path: ./nyalcf_core_extend
  dio: ^5.8.0+1
  args: ^2.6.0
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  import_sorter: ^4.6.0
