name: nyalcf
description: "[CLI]The next generation of LoCyanFrp launcher."
version: 0.0.3+3
homepage: https://nyalcf.1l1.icu
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  nyalcf_core:
    path: ../nyalcf_core
  nyalcf_env:
    path: ../nyalcf_env
  nyalcf_inject:
    path: ../nyalcf_inject
  dio: ^5.7.0
  args: ^2.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  import_sorter: ^4.6.0
