name: app_package_publisher
description: App package publisher
version: 0.3.6
homepage: https://distributor.leanflutter.org
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/app_package_publisher
publish_to: none

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  pubspec_parse: ^1.1.0
  shell_executor:
    path: ../shell_executor

dev_dependencies:
  dependency_validator: ^3.0.0
