# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Release

on:
  push:
    branches:
      - main
      - dev


jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        shell: pwsh
#        run: dart pub global activate -s path tools/flutter_distributor/packages/flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Setup Inno Setup 6
        shell: pwsh
        run: |-
          ./tools/is_setup.exe /VERYSLIENT
          Copy-Item "./tools/ChineseSimplified.isl" -Destination "C:\Program Files (x86)\Inno Setup 6\Languages"
      - name: Pack EXE Installer
        run: flutter_distributor package --platform windows --target exe

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build-Artifact
          path: build

      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Dist-Artifact
          path: dist


  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev rpm libayatana-appindicator3-dev patchelf locate libfuse2
          dart pub global activate -s path tools/flutter_distributor/packages/flutter_distributor
          flutter pub get

      - name: Setup AppImageTool
        run: |-
          sudo mv tools/appimagetool-x86_64.AppImage /usr/local/bin/appimagetool
          sudo chmod a+x /usr/local/bin/appimagetool

      - name: Pack Installers
        run: flutter_distributor package --platform linux --targets appimage,deb,rpm

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Build-Artifact
          path: build

      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Dist-Artifact
          path: dist


  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Dependencies
        run: |-
          flutter pub get
          npm install -g appdmg
          dart pub global activate -s path tools/flutter_distributor/packages/flutter_distributor

      - name: Pack DMG Installer
        run: flutter_distributor package --platform macos --target dmg

      - uses: actions/upload-artifact@v4
        with:
          name: macOS-Build-Artifact
          path: build

      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Dist-Artifact
          path: dist

  Release:
    runs-on: ubuntu-latest

    needs:
      - windows
      - linux
      - macos

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Shanghai'

      - name: Install Tools
        run: |- 
          sudo snap install yq

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Fetch Version
        run: |
          cd repo
          nyalcf_version=$(yq eval '.version' pubspec.yaml)
          echo "NyaLCF_VERSION=$nyalcf_version" >> $GITHUB_ENV
          cd ..
          ls Windows-Dist-Artifact/${{ env.NyaLCF_VERSION}}/
          ls Linux-Dist-Artifact/${{ env.NyaLCF_VERSION}}/
          ls macOS-Dist-Artifact/${{ env.NyaLCF_VERSION}}/

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ./repo/ChangeLog.md
          prerelease: false
          draft: false
          tag_name: v${{ env.NyaLCF_VERSION }}
          files: |
            Windows-Dist-Artifact/${{ env.NyaLCF_VERSION}}/nyalcf-${{ env.NyaLCF_VERSION}}-windows-setup.exe
            Linux-Dist-Artifact/${{ env.NyaLCF_VERSION}}/nyalcf-${{ env.NyaLCF_VERSION}}-linux.AppImage
            Linux-Dist-Artifact/${{ env.NyaLCF_VERSION}}/nyalcf-${{ env.NyaLCF_VERSION}}-linux.deb
            Linux-Dist-Artifact/${{ env.NyaLCF_VERSION}}/nyalcf-${{ env.NyaLCF_VERSION}}-linux.rpm
            macOS-Dist-Artifact/${{ env.NyaLCF_VERSION}}/nyalcf-${{ env.NyaLCF_VERSION}}-macos.dmg
