# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build CLI

on:
  push:
    branches:
      - main
      - dev

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        shell: pwsh
        run: |-
          cd nyalcf_cli
          dart pub get
          cd ..

      - name: Compile CLI
        run: |-
          cd nyalcf_cli
          dart compile exe bin/nyalcf_cli.dart -o build/nyalcf_cli.exe
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Artifact
          path: nyalcf_cli/build

  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        shell: pwsh
        run: |-
          cd nyalcf_cli
          dart pub get
          cd ..

      - name: Compile CLI
        run: |-
          cd nyalcf_cli
          dart compile exe bin/nyalcf_cli.dart -o build/nyalcf_cli
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux Artifact
          path: nyalcf_cli/build

  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        shell: pwsh
        run: |-
          cd nyalcf_cli
          dart pub get
          cd ..

      - name: Compile CLI
        run: |-
          cd nyalcf_cli
          dart compile exe bin/nyalcf_cli.dart -o build/nyalcf_cli
          cd ..    

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacOS Artifact
          path: nyalcf_cli/build
